services:
  chat-postgres:
    container_name: chat-postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - chat-app

volumes:
  postgres_data:

networks:
  chat-app:
